### ISSUE TITLE
Normalize address input

### ISSUE THREAD

**Issue by ianprime0509** [revaturelabs/rideshare-map-service#32]
The front-end is using the Google Maps address autocomplete functionality, so users should generally be dealing with very uniform data, but there's always the chance that someone may bypass this by ignoring the autocomplete. To reduce the number of extraneous entries in the geolocation cache (and potentially the route cache, if implemented: https://github.com/revaturelabs/rideshare-map-service/issues/31), we could normalize the address input.

Here are some potential normalizations, in increasing order of difficulty:

1. Strip unnecessary whitespace (leading and trailing, and preserve only one space between words).
2. Convert all characters to uppercase or lowercase (or anything else, really, as long as it's consistent).
3. Strip out unnecessary information like zip code (this one may be nearly impossible to do correctly; please don't just remove all five-digit numbers, because then people's house numbers will be removed as well).

**Comment by jsagreroperez** [comment]
A validator function was added into the package com.revature.rideforce.maps.validate package which normalizes the address string
